apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-env
data:
  APP_SECRET: 'jg_youtube_tutorial'
  MONGODB_URI: 'mongodb://34.30.76.14/msytt_shopping'
  MSG_QUEUE_URL: 'amqp://34.30.76.14:5672'
  EXCHANGE_NAME: 'ONLINE_STORE'
  PORT: '8003'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: bs6bs6/shopping-microservice:v1.1
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: shopping-env
        
