apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-env
data:
  APP_SECRET: 'jg_youtube_tutorial'
  MONGODB_URI: 'mongodb://34.30.76.14/msytt_customer'
  MSG_QUEUE_URL: 'amqp://34.30.76.14:5672'
  EXCHANGE_NAME: 'ONLINE_STORE'
  PORT: '8001'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: bs6bs6/customer-microservice:v1.1
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: customer-env
        
